version: '3.4'

services:
  fastfeet.api:
    image: ${DOCKER_REGISTRY-}fastfeet
    container_name: fastfeet.api
    build:
      context: .
      dockerfile: src/FastFeet.Api/Dockerfile
    ports:
      - "5002:5002"
      - "5001:5001"
  fastfeet.database:
    image: postgres:15-alpine
    container_name: fastfeet.database
    environment:
        - POSTGRES_DB=fastfeet
        - POSTGRES_USER=dev
        - POSTGRES_PASSWORD=dev
    volumes:
        - ./.container/fastfeet-db:/var/lib/postgresql/data
    ports:
        - 5432:5432
  fastfeet.seq:
    image: datalust/seq:latest
    container_name: fastfeet.seq
    environment:
        - ACCEPT_EULA=Y
    ports:
        - 5341:5341
        - 8081:80